# This file is auto-generated by Swagger Codegen (https://github.com/swagger-api/swagger-codegen)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'IO.Swagger PassApi' {
    Context 'PassApi' {
        It 'Invoke-PassApiCreateOrUpdatePass' {
            $ret = Invoke-PetApiGetPetById -passTypeId "TEST_VALUE" -passId "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'PassApi' {
        It 'Invoke-PassApiDeletePass' {
            $ret = Invoke-PetApiGetPetById -passTypeId "TEST_VALUE" -passId "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'PassApi' {
        It 'Invoke-PassApiGetPass' {
            $ret = Invoke-PetApiGetPetById -passTypeId "TEST_VALUE" -passId "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'PassApi' {
        It 'Invoke-PassApiPassList' {
            $ret = Invoke-PetApiGetPetById -passTypeId "TEST_VALUE" -page "TEST_VALUE" -limit "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'PassApi' {
        It 'Invoke-PassApiPassSync' {
            $ret = Invoke-PetApiGetPetById -passTypeId "TEST_VALUE"
            #$ret | Should BeOfType IO.Swagger.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
